require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'simple_endpoint.gemspec'

Style/Documentation:
  Enabled: false

Layout/LineLength:
    Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  IgnoredMethods: ['describe','context']

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
