version: 2.1

executors:
  test_executor:
    docker:
      - image: ${RUBY_VERSION}
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/simple_endpoint

jobs:
  build:
    environment:
      RUBY_VERSION: << parameters.ruby_version >>
      BUNDLER_VERSION: 2.1.4
    executor: test_executor
    parameters:
      ruby_version:
        type: string
    steps:
      - checkout

      - run:
          name: 'Install bundler'
          command: 'gem install bundler'

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run:
          name: Run Rubocop
          command: bundle exec rubocop

      - run:
          name: Run Tests
          command: bundle exec rspec

workflows:
  build_and_test:
    jobs:
      - build:
          name: 'ruby 2.6.8'
          ruby_version: circleci/ruby:2.6.8
      - build:
          name: 'ruby 2.7.0'
          ruby_version: circleci/ruby:2.7.0
      - build:
          name: 'ruby 3.0.3'
          ruby_version: circleci/ruby:3.0.3
      - build:
          name: 'ruby 3.1.2'
          ruby_version: cimg/ruby:3.1.2
